Front-End/portaVoz.View/Models/ErrorViewModel.cs
using System;

namespace portaVoz.View.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Front-End/portaVoz.View/Controllers/AvaliacoesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using portaVoz.Business.Impl;
using portaVoz.DAL;
using portaVoz.DAL.Domain.Repository;
using System;
using portaVoz.Models;

namespace portaVoz.View.Controllers
{
    public class AvaliacoesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConnectionString _configConnect;
        private AvaliacaoBSS _business;

        public AvaliacoesController(ILogger<HomeController> logger, IConnectionString configConnect)
        {
            _= configConnect ?? throw new ArgumentNullException(nameof(configConnect));
            _configConnect = configConnect;

            using OracleConnectionFactory connectionFactoryFiapOn = new OracleConnectionFactory(_configConnect.Conexao().FiapOn);
            _logger = logger;
            _business = new AvaliacaoBSS(connectionFactoryFiapOn);
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Listar(int idEntidade)
        {
            var avaliacoes = _business.ListarPorEntidade(idEntidade);
            return View("Index", avaliacoes);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [ActionName("Cadastro")]
        public IActionResult Cadastrar(AvaliacaoMO avaliacao)
        {
            avaliacao.AvaliadorResideLocal = avaliacao.AvaliadorResideLocal == "true" ? "S" : "N";
            _business.Adicionar(avaliacao);
            return View("Index");
        }

        public IActionResult Excluir(int id)
        {
            _business.Excluir(id);
            return View("Index");
        }

        public IActionResult Obter(int id)
        {
            throw new NotImplementedException();
        }
    }
}

Front-End/portaVoz.View/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using portaVoz.Business.Impl;
using portaVoz.DAL;
using portaVoz.DAL.Domain.Repository;
using System;

namespace portaVoz.View.Controllers
{
    public class DepartamentosController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConnectionString _configConnect;
        private TipoEntidadeBSS _business;

        public DepartamentosController(ILogger<HomeController> logger, IConnectionString configConnect)
        {
            _= configConnect ?? throw new ArgumentNullException(nameof(configConnect));
            _configConnect = configConnect;

            using OracleConnectionFactory connectionFactoryFiapOn = new OracleConnectionFactory(_configConnect.Conexao().FiapOn);
            _logger = logger;
            _business = new TipoEntidadeBSS(connectionFactoryFiapOn);
        }

        public IActionResult Index()
        {
            var tipos = _business.Listar();
            return View(tipos);
        }
    }
}

Front-End/portaVoz.View/Controllers/EntidadesPublicasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using portaVoz.Business.Impl;
using portaVoz.DAL;
using portaVoz.DAL.Domain.Repository;
using System;

namespace portaVoz.View.Controllers
{
    public class EntidadesPublicasController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConnectionString _configConnect;
        private EntidadePublicaBSS _business;

        public EntidadesPublicasController(ILogger<HomeController> logger, IConnectionString configConnect)
        {
            _= configConnect ?? throw new ArgumentNullException(nameof(configConnect));
            _configConnect = configConnect;

            using OracleConnectionFactory connectionFactoryFiapOn = new OracleConnectionFactory(_configConnect.Conexao().FiapOn);
            _logger = logger;
            _business = new EntidadePublicaBSS(connectionFactoryFiapOn);
        }

        public IActionResult Index()
        {
            var entidades = _business.Listar();
            return View(entidades);
        }

        public JsonResult Listar()
        {
            var entidades = _business.Listar();
            return Json(entidades);
        }
    }
}

Front-End/portaVoz.View/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using portaVoz.View.Models;

namespace portaVoz.View.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Front-End/portaVoz.View/Views/Avaliacoes/Cadastrar.cshtml
@model portaVoz.Models.AvaliacaoMO;
@{
    ViewData["Title"] = "Cadastrar Avaliações";
}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            Cadastrar Avaliações
        </div>
        <div class="card-body">
            <form asp-controller="Avaliacoes" asp-action="Cadastro" method="post">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="form-group">
                    @Html.DisplayNameFor(model => model.NomeAvaliador) : <input class="form-control" asp-for="NomeAvaliador" /> <br />
                    <span asp-validation-for="NomeAvaliador"></span><br />
                </div>
                <div class="form-group">
                    @Html.DisplayNameFor(model => model.IdadeAvaliador) : <input class="form-control" asp-for="IdadeAvaliador" /><br />
                    <span asp-validation-for="IdadeAvaliador"></span><br />
                </div>
                <div class="form-group">
                    Entidade Pública : <select class="form-control" id="entidade" name="idEntidade" required>
                        <option value="0" disabled selected>--Selecione uma Entidade Pública--</option>
                    </select>
                    <span asp-validation-for="IdEntidade"></span><br />
                </div>
                <div class="form-group">
                    @Html.DisplayNameFor(model => model.AvaliadorResideLocal) : <input class="ml-4" type="checkbox" asp-for="AvaliadorResideLocal" /><br />
                    <span asp-validation-for="AvaliadorResideLocal"></span><br />
                </div>
                <div class="form-group">
                    @Html.DisplayNameFor(model => model.Nota) : <input class="form-control" type="number" asp-for="Nota" /><br />
                    <span asp-validation-for="Nota"></span><br />
                </div>
                <button class="btn btn-primary" type="submit">Register</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        fetch('/EntidadesPublicas/Listar')
        .then(response => response.json())
        .then(result =>
        {
            let entidade = $("#entidade");
            for(var i = 0; i < result.length; i++)
            {
                let opt = document.createElement("option");
                opt.value = result[i].id
                opt.text = result[i].nome
                entidade.append(opt);
            }
        })
    });
</script>

Front-End/portaVoz.View/Views/Avaliacoes/Index.cshtml
@* @model portaVoz.Models.AvaliacaoMO; *@
@model IEnumerable<portaVoz.Models.AvaliacaoMO>
@{
    ViewData["Title"] = "Avaliações";
}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            Avaliações
        </div>
        <div class="card-body">
            <p>
                @Html.ActionLink("Cadastrar", "Cadastrar", "Avaliacoes")
            </p>
            <form class="form-inline" asp-controller="Avaliacoes" asp-action="Listar" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group mx-sm-3 mb-2">
                    <label for="entidade" class="sr-only">Entidade</label>
                    <select class="form-control" id="entidade" name="idEntidade" required>
                        <option value="0" disabled selected>--Selecione uma Entidade Pública--</option>
                    </select>
                    <div class="invalid-feedback">
                        Please choose a username.
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mb-2">Procurar</button>
            </form>
            <div class="mt-3">
                <table id="avaliacoes" class="table table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Id)</th>
                            <th>@Html.DisplayNameFor(model => model.NomeAvaliador)</th>
                            <th>@Html.DisplayNameFor(model => model.IdadeAvaliador)</th>
                            <th>@Html.DisplayNameFor(model => model.DtAvaliacao)</th>
                            <th>@Html.DisplayNameFor(model => model.IdEntidade)</th>
                            <th>@Html.DisplayNameFor(model => model.AvaliadorResideLocal)</th>
                            <th>@Html.DisplayNameFor(model => model.Nota)</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (@Model != null)
                        {
                            @foreach (var item in @Model)
                            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NomeAvaliador)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdadeAvaliador)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DtAvaliacao)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdEntidade)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AvaliadorResideLocal)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nota)
                            </td>
                            <td>
                                <a href="#">Edit</a> |
                                <a asp-action="Excluir" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        fetch('/EntidadesPublicas/Listar')
            .then(response => response.json())
            .then(result => {
                let entidade = $("#entidade");
                for (var i = 0; i < result.length; i++) {
                    let opt = document.createElement("option");
                    opt.value = result[i].id
                    opt.text = result[i].nome
                    entidade.append(opt);
                }
            });
        $('#avaliacoes').DataTable(
            {
                "language": {
                    "lengthMenu": "Mostrando _MENU_ itens por pagina",
                    "zeroRecords": "Nada encontrado - desculpe",
                    "info": "Mostrando pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "Não há dados disponíveis",
                    "infoFiltered": "(filtrando de _MAX_ total linhas)",
                    "search": "Procurar:",
                    "sPrevius": "Anterior",
                    "paginate": {
                        "previous": 'Anterior',
                        "next": 'Próximo'
                    }
                }
            }
        );
    });
</script>

Front-End/portaVoz.View/Views/Departamentos/Gerenciar.cshtml
@{
    ViewData["Title"] = "Gerenciar Departamentos";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Front-End/portaVoz.View/Views/Departamentos/Index.cshtml
@model IEnumerable<portaVoz.Models.TipoEntidadeMO>
@{
    ViewData["Title"] = "Departamentos";
}

<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            Departamentos
        </div>
        <div class="card-body">
            <div class="mt-3">
                <table id="avaliacoes" class="table table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Id)</th>
                            <th>@Html.DisplayNameFor(model => model.Nome)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in @Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Nome)
                                </td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Front-End/portaVoz.View/Views/EntidadesPublicas/Gerenciar.cshtml
@{
    ViewData["Title"] = "Gerenciar Entidades Públicas";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Front-End/portaVoz.View/Views/EntidadesPublicas/Index.cshtml
@{
    ViewData["Title"] = "Entidades Públicas";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Front-End/portaVoz.View/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Front-End/portaVoz.View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - portaVoz.View</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">portaVoz.View</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Avaliacoes" asp-action="Index">Avaliações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departamentos" asp-action="Index">Departamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EntidadesPublicas" asp-action="Index">Entidades Públicas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - portaVoz.View - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>